export const productsList = [
    {
        id: 1,
        src: "/assets/image.png",
        alt: "Bell 1",
        category: "Bells",
        name: "Bell 1",
        desc: "A beautiful bell with a rich sound.",
        new: false,
        price: 599,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 2,
        src: "/assets/image12.png",
        alt: "Bell 2",
        category: "Bells",
        name: "Bell 2",
        desc: "A beautiful bell with a rich sound.",
        new: false,
        price: 699,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 3,
        src: "/assets/image13.png",
        alt: "Bell 3",
        category: "Bells",
        name: "Bell 3",
        desc: "A beautiful bell with a rich sound.",
        new: true,
        price: 799,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 4,
        src: "/assets/image14.png",
        alt: "Flower 1",
        category: "Flowers",
        name: "Flower 1",
        desc: "A beautiful flower with vibrant colors.",
        new: false,
        price: 149,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 5,
        src: "/assets/image15.png",
        alt: "Flower 2",
        category: "Flowers",
        name: "Flower 2",
        desc: "A beautiful flower with vibrant colors.",
        new: false,
        price: 199,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 6,
        src: "/assets/image16.png",
        alt: "Flower 3",
        category: "Flowers",
        name: "Flower 3",
        desc: "A beautiful flower with vibrant colors.",
        new: true,
        price: 249,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 7,
        src: "/assets/image17.png",
        alt: "Vase 1",
        category: "Vases",
        name: "Vase 1",
        desc: "A beautiful vase for your flowers.",
        new: true,
        price: 399,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 8,
        src: "/assets/image18.png",
        alt: "Vase 2",
        category: "Vases",
        name: "Vase 2",
        desc: "A beautiful vase for your flowers.",
        new: false,
        price: 499,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 9,
        src: "/assets/image19.png",
        alt: "Vase 3",
        category: "Vases",
        name: "Vase 3",
        desc: "A beautiful vase for your flowers.",
        new: true,
        price: 599,
        sale: { state: true, price: 499, damage: "Chip on the rim" },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 10,
        src: "/assets/image20.png",
        alt: "Plate 1",
        category: "Plates",
        name: "Plate 1",
        desc: "A beautiful plate for your dining table.",
        new: false,
        price: 299,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],

    }, 
    {
        id: 11,
        src: "/assets/image21.png",
        alt: "Plate 2",
        category: "Plates",
        name: "Plate 2",
        desc: "A beautiful plate for your dining table.",
        new: false,
        price: 349,
        sale: { state: false, price: 0, damage: null },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    },
    {
        id: 12,
        src: "/assets/image.png",
        alt: "Plate 3",
        category: "Plates",
        name: "Plate 3",
        desc: "A beautiful plate for your dining table.",
        new: true,
        price: 399,
        sale: { state: true, price: 299, damage: "Small scratch" },
        sizes: ["S", "M", "L"],
        colors: ["Red", "Blue", "Green"],
    }
]